### ISSUE TITLE
Some issue with messages buffer

### ISSUE THREAD

**Issue by pertinaxwallet** [markgenuine/ever-client-go#53]
This is a piece of code that can reproduce the issue below:
```golang
package main

import (
	"encoding/json"
	"fmt"
	"log"
	"testing"
	"time"

	"github.com/move-ton/ever-client-go/domain"
	"github.com/move-ton/ever-client-go/gateway/client"
	everNet "github.com/move-ton/ever-client-go/usecase/net"
	"github.com/stretchr/testify/assert"
)

func TestNet(t *testing.T) {

	config := domain.NewDefaultConfig("", domain.GetDevNetBaseUrls())
	clientConn, err := client.NewClientGateway(config)
	assert.Equal(t, nil, err)
	defer clientConn.Destroy()

	netUC := everNet.NewNet(config, clientConn)

	t.Run("TestSubscribeCollection", func(t *testing.T) {

		// # Prepare query
		nowTime := int(time.Now().Unix())
		queryParams := &domain.ParamsOfSubscribeCollection{
			Collection: "messages",
			Filter:     json.RawMessage(fmt.Sprintf(`{"created_at":{"gt":%d}}`, nowTime)),
			Result:     "id, src, dst, boc, body, msg_type, value(format:DEC), created_at",
		}

		// # Create generator
		generator, handle, err := netUC.SubscribeCollection(queryParams)
		assert.NotNil(t, generator)
		assert.Equal(t, nil, err)
		assert.NotNil(t, handle)
		log.Println("messages")
		go func() {
			for g := range generator {
				defer netUC.Unsubscribe(&domain.ResultOfSubscribeCollection{Handle: handle.Handle})
				log.Println(string(g))
			}
		}()
		time.Sleep(2 * time.Minute)
	})
}
```

Result of work:
`
2022/08/18 13:44:11 result{"id":"edd2fabca392474bd902a774c37e5f79750b3c15effc2bd86052094b9937ddc4","src":"","dst":"0:c0d158e97b7c7f2d72d0dd4dacd6cd690d08c131a718b9b445d432c9a19e5466","boc":"te6ccgEBAQEAeQAA7YgBgaKx0vb4/lrlobqbWa2a0hoRgmNOMXNoi6hlk0M8qMwES/w5EKLtn87bMJXe+1OVoV1EIapS2EWiYr6Cbsu1PNJfI+JeFe8JkZpxwjlRmNMTuClHFIzu5K5D9tWpoXQUPAAABgrCNiuZi/hguH6TaLWL+F7e","body":"te6ccgEBAQEAVwAAqYl/hyIUXbP522YSu99qcrQrqIQ1SlsItExX0E3ZdqeaS+R8S8K94TIzTjhHKjMaYncFKOKRndyVyH7atTQugoeAAADBWEbFczF/DBcP0m0WsX8L28A=","msg_type":1,"value":null,"created_at":1660819444}

2022/08/18 13:44:11 result{"id":"5f425a19cfc52e85d472a4bf2aea1f591dda4b6e67dbd41c26c3e631faad0c73","src":"","dst":"0:802f5476cc99425184757c0672fe7737e94b3cbc2cee59e156dfe61c0c0c630c","boc":"te6ccgEBAQEAeQAA7YgBAF6o7ZkyhKMI6vgM5fzub9KWeXhZ3LPCrb/MOBgYxhgEm5IdELY0uc1RECiRPifZRVawjUTq+V3jLvI2Xy9RcY2QV92tvUGQqvjfXeGgmwEVNcmAYQoWMNvy534Bajh4PAAABgrCNiqxi/hguH6TaLWL+F7a","body":"te6ccgEBAQEAVwAAqZNyQ6IWxpc5qiIFEifE+yiq1hGonV8rvGXeRsvl6i4xsgr7tbeoMhVfG+u8NBNgIqa5MAwhQsYbflzvwC1HDweAAADBWEbFVjF/DBcP0m0WsX8L20A=","msg_type":1,"value":null,"created_at":1660819443}

2022/08/18 13:44:11 {"id":"edd2fabca392474bd902a774c37e5f79750b3c15effc2bd86052094b9937ddc4","src":"","dst":"0:c0d158e97b7c7f2d72d0dd4dacd6cd690d08c131a718b9b445d432c9a19e5466","boc":"te6ccgEBAQEAeQAA7YgBgaKx0vb4/lrlobqbWa2a0hoRgmNOMXNoi6hlk0M8qMwES/w5EKLtn87bMJXe+1OVoV1EIapS2EWiYr6Cbsu1PNJfI+JeFe8JkZpxwjlRmNMTuClHFIzu5K5D9tWpoXQUPAAABgrCNiuZi/hguH6TaLWL+F7e","body":"te6ccgEBAQEAVwAAqYl/hyIUXbP522YSu99qcrQrqIQ1SlsItExX0E3ZdqeaS+R8S8K94TIzTjhHKjMaYncFKO

2022/08/18 13:44:11 {"id":"5f425a19cfc52e85d472a4bf2aea1f591dda4b6e67dbd41c26c3e631faad0c73","src":"","dst":"0:802f5476cc99425184757c0672fe7737e94b3cbc2cee59e156dfe61c0c0c630c","boc":"te6ccgEBAQEAeQAA7YgBAF6o7ZkyhKMI6vgM5fzub9KWeXhZ3LPCrb/MOBgYxhgEm5IdELY0uc1RECiRPifZRVawjUTq+V3jLvI2Xy9RcY2QV92tvUGQqvjfXeGgmwEVNcmAYQoWMNvy534Bajh4PAAABgrCNiqxi/hguH6TaLWL+F7a","body":"te6ccgEBAQEAVwAAqZNyQ6IWxpc5qiIFEifE+yiq1hGonV8rvGXeRsvl6i4xsgr7tbeoMhVfG+u8NBNgIqa5MAwhQsYbflzvwC1HDweAAADBWEbFVjF/DBcP0m0WsX8L20A=","msg_type":1,"value":null,"created_at":1660819443}

2022/08/18 13:44:11 {"id":"644213c1537a0c7cfe1ec41a2d9eca75ca8fb22f501fe0740ad790b39e120010","src":"","dst":"0:e0babd9c1c1532fcbaf16d8cec1a0e7af8aef4fb137d3599f124292ab90d8eae","boc":"te6ccgEBAQEAeQAA7YgBwXV7ODgqZfl14tsZ2DQc9fFd6fYm+msz4khSVXIbHVwGPDZrDAKmGD8mW2jzwXZPWkEUXuFD05zVJRYeBWHDLl1HjA7AHu7R7lSYvyAR7tkKAn8+aa3D/6RtCohOri40LAAABgrCNiuFi/hguH6TaLWL+F7i","body":"te6ccgEBAQEAVwAAqceGzWGAVMMH5MttHnguyetIIovcKHpzmqSiw8CsOGXLqPGB2APd2j3KkxfkAj3bIUBP5801uH/0jaFRCdXFxoWAAADBWEbFcLF/DBcP0m0WsX8L3EA=","msg_type":1,"value":null,"created_at":1660819444}

2022/08/18 13:44:11 result{"id":"644213c1537a0c7cfe1ec41a2d9eca75ca8fb22f501fe0740ad790b39e120010","src":"","dst":"0:e0babd9c1c1532fcbaf16d8cec1a0e7af8aef4fb137d3599f124292ab90d8eae","boc":"te6ccgEBAQEAeQAA7YgBwXV7ODgqZfl14tsZ2DQc9fFd6fYm+msz4khSVXIbHVwGPDZrDAKmGD8mW2jzwXZPWkEUXuFD05zVJRYeBWHDLl1HjA7AHu7R7lSYvyAR7tkKAn8+aa3D/6RtCohOri40LAAABgrCNiuFi/hguH6TaLWL+F7i","body":"te6ccgEBAQEAVwAAqceGzWGAVMMH5MttHnguyetIIovcKHpzmqSiw8CsOGXLqPGB2APd2j3KkxfkAj3bIUBP5801uH/0jaFRCdXFxoWAAADBWEbFcLF/DBcP0m0WsX8L3EA=","msg_type":1,"value":null,"created_at":1660819444}
`

The third messages were received as a piece of the buffer.

To print and compare results before sending to the channel and after, there was added the log message with "result" here https://github.com/markgenuine/ever-client-go/blob/master/usecase/net/net.go#L96
```golang
result := body.Result
log.Println("result" + string(result))
chanResult <- result
```

By the fact observes some inconsistent of data while data goes by the channel.

> go version go1.18.3 windows/amd64

**Comment by markgenuine** [comment]
Ok, i'm check it and if that do fix it.

**Comment by pertinaxwallet** [comment]
Maybe some approach from here will help to solve this issue https://stackoverflow.com/questions/37371206/golang-share-big-chunk-of-data-between-goroutines

**Comment by markgenuine** [comment]
@pertinaxwallet I didn't get same situation as you. 
Specify you enviroment: OS, Golang version, version binding.

P.s. attach file log with
[log.txt](https://github.com/markgenuine/ever-client-go/files/9740448/log.txt)
 my result test on devote, MacOs 12.5, Golang: 1.18.2, version lib 1.37.1
